# Generated by Django 5.2.4 on 2025-07-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackinghistory',
            old_name='cuurent_balance',
            new_name='current_balance',
        ),
    ]
