# Generated by Django 5.2.4 on 2025-07-12 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_cuurent_balance_trackinghistory_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='current_balance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.currentbalance'),
        ),
    ]
