# Generated by Django 5.2.4 on 2025-07-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_requestlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogs',
            name='request_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestlogs',
            name='request_path',
            field=models.CharField(max_length=100),
        ),
    ]
