# Generated by Django 5.2.4 on 2025-07-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
