# Generated by Django 5.2.4 on 2025-07-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_delete_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestLogs',
        ),
    ]
