# Generated by Django 5.2.4 on 2025-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_requestlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
