# Generated by Django 5.2.4 on 2025-07-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_trackinghistory_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinghistory',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='currentbalance',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='username',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to='tracker.currentbalance', to_field='username'),
            preserve_default=False,
        ),
    ]
